name: po_editor_downloader
description: CLI tool for a simple way of updating translations in Flutter from POEditor.
version: 0.4.0
homepage: https://github.com/teklund/po_editor_downloader

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  args: ^2.4.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.10
